name: Greetings
version: 1.1
author: James
main: me.james.greetings.Main
description: The greetings plugin lets you say hello and goodbye!  Simply type in the commands,
  and you will say either hello or goodbye to anyone in the server.

commands:
  hello:
    description: "Hello there Everyone!"
  goodbye:
    description: "Goodbye Everyone!!!!!"
  bye:
    description: "Goodbye who ever is out there!"
